resolver: lts-10.0
packages:
- ./auto-update
- ./mime-types
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./wai-app-static
- ./wai-handler-fastcgi
- ./wai-websockets
- ./wai-conduit
flags:
  wai-extra:
    build-example: true
extra-deps:
- bsb-http-chunked-0
- tls-session-manager-0.0.0.2
- psqueues-0.2.4.0
nix:
  enable: false
  packages:
  - fcgi
  - zlib
image:
  containers:
    - base: "fpco/pid1"
      name: "yesodweb/warp"
      executables:
        - warp
