resolver: lts-22.40
packages:
- ./auto-update
- ./mime-types
- ./recv
- ./time-manager
- ./wai
- ./wai-app-static
- ./wai-conduit
- ./wai-extra
- ./wai-frontend-monadcgi
- ./wai-http2-extra
- ./wai-websockets
- ./warp
- ./warp-quic
- ./warp-tls
flags:
  wai-extra:
    build-example: true
nix:
  enable: false
  packages:
  - fcgi
  - zlib
extra-deps:
  - crypto-token-0.1.2
  - http-semantics-0.2.0
  - http2-5.3.1
  - http3-0.0.16
  - network-control-0.1.0
  - network-udp-0.0.0
  - quic-0.2.4
  - sockaddr-0.0.1
  - tls-2.1.3
  - tls-session-manager-0.0.7
