resolver: lts-23.18
packages:
- ./auto-update
- ./mime-types
- ./recv
- ./time-manager
- ./wai
- ./wai-app-static
- ./wai-conduit
- ./wai-extra
- ./wai-frontend-monadcgi
- ./wai-http2-extra
- ./wai-websockets
- ./warp
- ./warp-quic
- ./warp-tls
flags:
  wai-extra:
    build-example: true
nix:
  enable: false
  packages:
  - fcgi
  - zlib
extra-deps:
  - ech-config-0.0.1
  - hpke-0.0.0
  - http3-0.1.0
  - network-control-0.1.7
  - quic-0.2.16
  - random-1.3.1
  - sockaddr-0.0.1
  - tls-2.1.10
  - websockets-0.13.0.0
