resolver: lts-2.17
packages:
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./wai-app-static
- ./wai-handler-fastcgi
- ./wai-handler-launch
- ./wai-websockets
- ./wai-conduit
- ./mime-types
- ./auto-update
- location:
    git: git@github.com:vincenthz/hs-tls
    commit: 7baaef9657b2154c935565767a01c166f6f4c77d
  subdirs:
  - core
extra-deps:
- doctest-0.10.1
- http2-1.0.2
- hex-0.1.2
- cryptonite-0.6
- x509-1.6.0
- x509-store-1.6.0
- x509-validation-1.6.0
- x509-system-1.6.0