resolver: lts-24.7
packages:
- ./auto-update
- ./mime-types
- ./recv
- ./time-manager
- ./wai
- ./wai-app-static
- ./wai-conduit
- ./wai-extra
- ./wai-frontend-monadcgi
- ./wai-http2-extra
- ./wai-websockets
- ./warp
- ./warp-quic
- ./warp-tls
flags:
  wai-extra:
    build-example: true
nix:
  enable: false
  packages:
  - fcgi
  - zlib
extra-deps:
  - ech-config-0.0.1
  - hpke-0.1.0
  - http-semantics-0.4.0
  - http2-5.4.0
  - http3-0.1.3
  - quic-0.3.0
  - ram-0.21.1
  - random-1.3.1
  - sockaddr-0.0.1
  - tls-2.3.0
