resolver: lts-13.14
packages:
- ./auto-update
- ./mime-types
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./wai-app-static
- ./wai-websockets
- ./wai-conduit
- ./time-manager
flags:
  wai-extra:
    build-example: true
nix:
  enable: false
  packages:
  - fcgi
  - zlib
image:
  containers:
    - base: "fpco/pid1"
      name: "yesodweb/warp"
      executables:
        - warp
extra-deps:
- fast-logger-3.0.0
- http2-2.0.0
- network-byte-order-0.1.1.0
- wai-logger-2.3.6
