resolver: lts-18.28
packages:
- ./auto-update
- ./mime-types
- ./wai
- ./wai-extra
- ./warp
- ./warp-tls
- ./wai-app-static
- ./wai-frontend-monadcgi
- ./wai-http2-extra
- ./wai-websockets
- ./wai-conduit
- ./time-manager
flags:
  wai-extra:
    build-example: true
nix:
  enable: false
  packages:
  - fcgi
  - zlib
extra-deps: []
