jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 180
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-11:
        BUILD: stack
        STACK_YAML: stack-lts-11.yaml
        ARGS: "--resolver lts-11"
      stack-lts-12:
        BUILD: stack
        STACK_YAML: stack-lts-12.yaml
        ARGS: "--resolver lts-12"
      stack-lts-14:
        BUILD: stack
        ARGS: "--resolver lts-14"
    maxParallel: 3
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -skL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin;
      export PATH=$HOME/.local/bin:$PATH
      stack --install-ghc $ARGS test --bench --only-dependencies
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
