name: Tests

on:
  push:
    branches: [ 'master', 'ci' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  stack:
    name: Stack
    runs-on: ${{ matrix.os }}
    env:
      STACK_PATHS_GLOBAL_WINDOWS: |
        C:\\sr
        %APPDATA%\stack
        %LOCALAPPDATA%\Programs\stack
      STACK_PATH_GLOBAL_UNIX: "~/.stack"
      STACK_PATH_LOCAL: ".stack-work"
      GHCUP_PATH_WINDOWS: "C:\\ghcup"
      GHCUP_PATH_MAC: "/Users/runner/.ghcup"
      GHCUP_PATH_LINUX: |
        /usr/local/.ghcup
        /home/runner/.ghcup

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        stack: ["latest"]
        resolver:
          - "nightly" # 9.12
          - "lts-24"  # 9.10
          - "lts-23"  # 9.8
          - "lts-22"  # 9.6
          - "lts-21"  # 9.4
          - "lts-20"  # 9.2

    steps:
      - name: "Set ENV vars per LTS"
        id: env-vars
        shell: bash
        run: |
          # First we decide which GHC and which LTS we build with

          STACKYAML="stack.yaml"
          GHC_VERSION="9.12"
          case "${{ matrix.resolver }}" in
            "nightly")
              STACKYAML="stack-nightly.yaml"
              ;;
            "lts-24")
              GHC_VERSION="9.10"
              ;;
            "lts-23")
              GHC_VERSION="9.8"
              STACKYAML="stack-lts-23.yaml"
              ;;
            "lts-22")
              GHC_VERSION="9.6"
              STACKYAML="stack-lts-22.yaml"
              ;;
            "lts-21")
              GHC_VERSION="9.4"
              STACKYAML="stack-lts-21.yaml"
              ;;
            "lts-20")
              GHC_VERSION="9.2"
              STACKYAML="stack-lts-20.yaml"
              ;;
            *)
              ;;
          esac

          # And then we expose these variables in the 'env'
          echo "STACKYAML=$STACKYAML" >> $GITHUB_ENV
          echo "GHC_VERSION=$GHC_VERSION" >> $GITHUB_ENV

      - name: Clone project
        uses: actions/checkout@v6

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: |-
            ${{ case(
              matrix.os == 'windows-latest', env.STACK_PATHS_GLOBAL_WINDOWS,
              env.STACK_PATH_GLOBAL_UNIX
            ) }}
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(env.STACKYAML) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      # Let's also try caching the build artifacts, so that rebuilds might go faster as well.
      - name: Cache local files
        uses: actions/cache@v6
        with:
          path: |
            ${{ env.STACK_PATH_LOCAL }}
          key: stack-work-${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(env.STACKYAML) }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            stack-work-${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles(env.STACKYAML) }}-
            stack-work-${{ runner.os }}-${{ matrix.resolver }}-

      - name: Cache GHCUP installs
        uses: actions/cache@v6
        with:
          path: |-
            ${{ case(
              matrix.os == 'windows-latest', env.GHCUP_PATH_WINDOWS,
              matrix.os == 'macos-latest', env.GHCUP_PATH_MAC,
              env.GHCUP_PATH_LINUX
            ) }}
          key: ghcup-${{ runner.os }}-${{ env.GHC_VERSION }}
          restore-keys: |
            ghcup-${{ runner.os }}-

      - uses: haskell-actions/setup@v2
        name: Setup Haskell Stack
        with:
          ghc-version: "${{ env.GHC_VERSION }}"
          stack-version: "${{ matrix.stack }}"
          enable-stack: true

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            EXTRA=""
            BENCH="--bench"
            if [[ ${{ matrix.os }} = "windows-latest" ]]; then
            EXTRA="--no-run-tests"
            elif [[ ${{ matrix.os }} = "macos-latest" ]]; then
            BENCH=""
            fi

            stack test \
              --system-ghc \
              --no-terminal \
              --resolver ${{ matrix.resolver }} \
              --haddock --no-haddock-deps \
              $BENCH --no-run-benchmarks \
              $EXTRA \
              --stack-yaml ${{ env.STACKYAML }}
